### ISSUE TITLE
[UI Feature] Use doc strings to populate description on Workflow search Ux

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyteconsole#294] opened 2021-10-15 15:59 UTC
### Motivation: Why do you think this is important?

The new Workflow search UX now displays various metadata about a workflow - included in that is a field for description.  We want to surface any "description" values user included in their documentation. 

see: https://docs.google.com/document/d/1m_-_QMloU7pLcnOQU8OUqfyGhPaBwB4XxYZiZIMOgq0/edit#

### Goal: What should the final outcome look like, ideally?

![Screen Shot 2021-10-15 at 8 58 34 AM](https://user-images.githubusercontent.com/84735036/137517643-eed02cda-93e6-41cf-863c-513921bde30b.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### On Fix notify threads:
https://flyte-org.slack.com/archives/CNMKCU6FR/p1645732559319929

**Comment by anrusina** [comment] 2022-03-03 00:46
Description should be taken from `namedEntity.metadata.description`

**Comment by anrusina** [comment] 2022-03-21 19:05
Similar description should be populated and shown for tasks, not sure if it uses the same field.

**Comment by wild-endeavor** [comment] 2022-03-24 22:09
I don't think this is a console issue - i think there's something fundamentally broken in the cycle.   The lifecycle for this process seems to be broken in general.  Currently we are pulling the docstrings and parsing them in flytekit, but they don't make their way to the database because the registration flow that flytectl(/flyte-cli) does doesn't include that text.  We'll have to rethink this.

cc @katrogan @EngHabu

**Comment by katrogan** [comment] 2022-03-24 22:10
can we hide the workflow description until this feature is out? it's always empty so there's no point in exposing it

**Comment by olga-union** [comment] 2022-03-25 15:06
@katrogan quick fix to stop rendering empty descriptions https://github.com/flyteorg/flyteconsole/issues/317

**Comment by cosmicBboy** [comment] 2023-03-16 18:29
dupe of https://github.com/flyteorg/flyte/issues/1683

**Closed by cosmicBboy** 2023-03-16 18:29 UTC
Labels: blocked, enhancement, ui
